import localFont from "next/font/local";
import Navbar from "@/Components/Navbar/page";
import dbConnect from "@/lib/dbConnect";
import "./globals.css";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Test",
  description: "Generated by create next app",
};
export async function connect() {
  await dbConnect();
}

//connect();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <head>
          <title>Prometheus</title>
        </head>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
